### ISSUE TITLE
Command error: info server

### ISSUE THREAD

**Issue by RobertTheReal** [RicoViking9000/Disguard#1]
The command `info server`first loads for a while, then this response is sent:

> An error occured while searching, please send this to my dev: 
[Errno 2] No such file or directory: 'Indexes/553336164375986186/614735260059435029'

**Comment by RicoViking9000** [comment]
I'm actively working on the next update in between higher priorities like school, and improving/fixing the info command is what I'm currently working on. Thank you for bringing this to my attention, this error usually doesn't come up, and it looks like the indexing code malfunctioned somewhere. Expect a fix in a week or less. I will also likely add a global error handler to the bot to send these errors directly to me

**Comment by RicoViking9000** [comment]
This is caused due to message indexing service (total posts count) and has been fixed as of 0.2.14.
