### ISSUE TITLE
Command error: info

### ISSUE THREAD

**Issue by RobertTheReal** [RicoViking9000/Disguard#2]
If you use the `info` command, but don't specify an argument, no error message will be returned, but the load emote will remain forever.
An error message or an explanation would be useful.

**Comment by RicoViking9000** [comment]
Thank you, I clearly didn't test empty strings with this. It won't load forever; it'll eventually say that the embed is too big to send. I have already coded a prerequisite of two-character searches in the future, and this will come out with the next update. Speaking of loading forever, next update should change the priorities of some actions, making the command execute much faster.

**Comment by RicoViking9000** [comment]
Has been fixed as of 0.2.14, but I forgot to close this
